{% set name = "ccache" %}
{% set version = "3.3.6" %}
{% set sha256 = "eac8d2a5055014bebae1434d9b7c66c25d64323800808c27a4534cee167e6bea" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.bz2
  url: https://www.samba.org/ftp/ccache/{{ name }}-{{ version }}.tar.bz2
  sha256: {{ sha256 }}

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - zlib 1.2.*
    - xz 5.2.*
  run:
    - zlib 1.2.*

test:
  commands:
    - ccache --help
    - ccache --version

about:
  home: https://ccache.samba.org/
  license: GPL-3.0
  summary: 'a compiler cache'

  description: |
    ccache is a compiler cache. It speeds up recompilation by caching
    previous compilations and detecting when the same compilation is
    being done again. Supported languages are C, C++, Objective-C and Objective-C++.
  doc_url: https://ccache.samba.org/manual.html
  dev_url: https://github.com/ccache/ccache

extra:
  recipe-maintainers:
    - edisongustavo
