{% set name = "ccache" %}
{% set version = "4.11.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/{{ name }}/{{ name }}/releases/download/v{{ version }}/{{ name }}-{{ version }}.tar.gz
  sha256: 28a407314f03a7bd7a008038dbaffa83448bc670e2fc119609b1d99fb33bb600

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - pkg-config
    - ninja-base
  host:
    - fmt {{ fmt }}
    - doctest 2.4.11
    - libhiredis 1.3.0
    - zstd {{ zstd }}
    - xxhash {{ xxhash }}
    - ucrt 10.0.20348.0  # [win]
  run:
    - libhiredis
    - ucrt  # [win]
    
test:
  commands:
    - ccache --help
    - ccache --version

about:
  home: https://ccache.dev
  summary: A compiler cache
  license: GPL-3.0-only
  license_family: GPL
  license_file: GPL-3.0.txt
  description: |
    ccache is a compiler cache. It speeds up recompilation by caching
    previous compilations and detecting when the same compilation is
    being done again. Supported languages are C, C++, Objective-C and Objective-C++.
  doc_url: https://ccache.dev/manual/latest.html
  dev_url: https://github.com/ccache/ccache

extra:
  recipe-maintainers:
    - edisongustavo
    - marcelotrevisani
    - mingwandroid
