{% set name = "ccache" %}
{% set version = "3.7.7" %}  # [not win]
{% set fork = "ccahe" %}  # [not win]
{% set version = "3.7.1" %}  # [win]
{% set fork = "cristianadam" %}  # [win]

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/{{ fork }}/{{ fork }}/releases/download/v{{ version }}/{{ name }}-{{ version }}.tar.gz  # [not win]
  sha256: 9b61f7fab2ec15305ee8382b03365503232dfb04b57414e7b0433768d530fa8a  # [not win]
  # folder: ccache.{{ fork }}
  # path: W:/src/ccache.{{ fork }}
  # path_via_symlink: True
  git_url: https://github.com/{{ fork }}/{{ name }}.git  # [win]
  git_tag: 7931393c825cd4e9a161ffd405d0756e7e628f0e  # [win]
  patches:
    - 0001-CMAKE_VERBOSE_MAKEFILE_ON.patch
    - 0002-Use-Unix-code-for-find_executable_in_path.patch

build:
  number: 2

requirements:
  build:
    - {{ compiler('c') }}  # [not win]
    - {{ compiler('cxx') }}  # [not win]
    - m2w64-toolchain  # [win]
    - make  # [not win]
    - cmake  # [win]
    - ninja  # [win]
    - git  # [win]
    - patch  # [not win]
    - m2-patch  # [win]
  host:
    - zlib  # [not win]
    - xz  # [not win]

test:
  requires:
    - {{ compiler('c') }}
  commands:
    # 1. Tests that it runs at all
    - ccache --help
    - ccache --version
    # 1.1. We need to test both ccache and ccache.exe on Windows.
    - ccache.exe --help  # [win]
    - ccache.exe --version  # [win]
    # 2. Test finding and launching a C compiler:
    - ccache ${CC}  # [not win]
    - ccache cl.exe  # [win]
    - ccache cl  # [win]
    # We could consider some tests to see that we actually cache compilations!

about:
  home: https://ccache.samba.org/
  license: GPL-3.0
  license_family: GPL
  license_file: ccache.{{ fork }}/GPL-3.0.txt
  summary: 'A compiler cache'

  description: |
    ccache is a compiler cache. It speeds up recompilation by caching
    previous compilations and detecting when the same compilation is
    being done again. Supported languages are C, C++, Objective-C and Objective-C++.
  doc_url: https://ccache.samba.org/manual.html
  dev_url: https://github.com/ccache/ccache

extra:
  recipe-maintainers:
    - edisongustavo
    - marcelotrevisani
    - mingwandroid
