travis:
  secure:
    BINSTAR_TOKEN: jCX99Ho3dgxDTb1gGf/mXXLwPNafpRoVG6LpfH7vdVCnNh5i+53Yg9Fy3iGsxSvUV7qihd+S72K7jRP++ssAAW2YNRZZk8bmiopcAa31kta7EZrPRjU5bUXyBQ+0GL54EzqT6q287FAuHZXbJ+SiPUK/dIfInk7UbU/L4sB+Q5jYqolUw8AkOHmKasoFnKOJKJ7U+gXMI8nJcY9ONbOh/yk1GoYxOE8kWpCWmeU9tWt+StaksAvlizLxPfY/mIsTiTBj17ahPcK4QGirZeq67H2rnCeDmhALuk2tk01VmuW3yxiJ+YMAkrFlUMi8kFER4aaKR5WJblUnPVDjzmtSokiLPT0RMvFj1JsazjXpWK4KnSC1kx4AitAgSE22KBCmA889syaF1Aac9MyQDscCp6TAYZalz1m4isrYOjXIPOkAP7kryDM1whTYUp7u5Gf3cHLPbfDfwec7opJXXlnOlMqTHjUMcyhvNcFmEq5k/FIHjWt96hHjrxbEIW+Pmq9Gd4AKKx8ipxktSkPJkU/OpY4QLOs5AE1LGWZ8Bixt9nPmNk5bPewsNYy/iJdL8Hd1u8X8omqa3G/mHN2D3obrffYvNJKcERJe+CchEA3S/2GPZ6toEOvB3cMQhNQQdX9Pk2Y1VwD0ywAJG3N/FY0p0dPlps1TYizWm/K45RDcI/Y=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
